services:
    location:
        image: dagbjorn/microcoffeeoncloud-location:1.0.0-SNAPSHOT
        ports:
            - "8081:8081"
            - "8444:8444"
        depends_on:
            - mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery
    mongodb:
        image: dagbjorn/microcoffeeoncloud-database:1.0.0-SNAPSHOT
        command: mongod --bind_ip_all --tlsMode preferTLS --tlsCertificateKeyFile /microcoffee.study-key.pem --setParameter tlsUseSystemCA=true --tlsAllowConnectionsWithoutCertificates
        ports:
            - "27017:27017"
            - "28017:28017"
        domainname: microcoffee.study
        volumes:
            - mongodbdata:/data/db
        networks:
            microcoffee:
                aliases:
                    - database.microcoffee.study

volumes:
    mongodbdata:
        external: true

networks:
    microcoffee:
    configserver:
        name: microcoffeeoncloud-configserver_configserver
        external: true
    discovery:
        name: microcoffeeoncloud-discovery_discovery
        external: true
