---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
      - name: location
        image: dagbjorn/microcoffeeoncloud-location:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /internal/isready
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /internal/isalive
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 8081
        - containerPort: 8444
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "devgke"
        - name: SPRING_CLOUD_CONFIG_URI
#          value: "http://configserver.default:8091"
          value: "https://configserver.default:8454"
---
apiVersion: v1
kind: Service
metadata:
  name: location
  labels:
    app: location
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      name: config-http
    - port: 8444
      targetPort: 8444
      nodePort: 30444
      name: config-https
  selector:
    app: location
    