---
apiVersion: v1
kind: Service
metadata:
  name: microcoffee-mongodb
  labels:
    app: microcoffee
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
    - port: 28017
      targetPort: 28017
      name: mongodb-extra
  selector:
    app: microcoffee
    tier: backend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: microcoffee-mongodb
  labels:
  labels:
    app: microcoffee
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microcoffee
        tier: backend
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.1
          ports:
            - containerPort: 27017
              hostPort: 27017
            - containerPort: 28017
              hostPort: 28017
          volumeMounts:
            - name: mongodbdata
              mountPath: /data/db
      volumes:
        - name: mongodbdata
          hostPath:
            path: /mnt/sda1/data/mongodbdata
