version: 2
updates:
  # Configurations for Dockerfile
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-authserver"
    schedule:
      interval: "daily"
      time: "06:00"
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-configserver"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # Ignore major version updates
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-creditrating"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # Ignore major version updates
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-database"
    schedule:
      interval: "daily"
      time: "06:00"
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-discovery"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # Ignore major version updates
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-gateway"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # Ignore major version updates
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-location"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # Ignore major version updates
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/microcoffeeoncloud-order"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # Ignore major version updates
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"

  # Configuration for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    ignore:
      # wro4j-maven-plugin related version conflict. Keep current version.
      - dependency-name: "org.webjars.npm:glob"
