version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:20"

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:20"

  # Configuration for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:20"
