tag-prefix: 'microcoffeeoncloud-'
tag-template: 'microcoffeeoncloud-$RESOLVED_VERSION'
name-template: 'microcoffeeoncloud-$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '⬆️ Dependency upgrades'
    labels:
      - 'bump'
      - 'dependencies'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'

template: |
  ## What's Changed
  $CHANGES
