tag-prefix: 'microcoffeeoncloud-'
tag-template: 'microcoffeeoncloud-$NEXT_PATCH_VERSION'
name-template: '$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    when:
      - labels:
          - 'feature'
          - 'enhancement'
  - title: '⚠️ Breaking Changes'
    when:
      - labels:
          - 'breaking'
  - title: '🐛 Bug Fixes'
    when:
      - labels:
          - 'fix'
          - 'bugfix'
          - 'bug'
  - title: '🧰 Maintenance'
    when:
      - labels:
          - 'chore'
  - title: '⬆️ Dependency upgrades'
    when:
      - labels:
          - 'bump'
          - 'dependencies'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'

template: |
  ## What's Changed
  $CHANGES
