swagger: '2.0'
info:
    description: '[FROM CUSTOM SPEC] Finds the coffee shop closest to the current
        position.'
    version: '1.0'
    title: Location API
    contact:
        name: Dagbjørn Nogva
        url: https://github.com/dagbjorn
    license: {
        }
host: localhost:8444
basePath: /
tags:
-   name: Location
paths:
    /api/coffeeshop/nearest/{latitude}/{longitude}/{maxdistance}:
        get:
            tags:
            - Location
            summary: Get nearest coffee shop closest to the current position.
            operationId: getNearestCoffeeShop
            produces:
            - application/json;charset=UTF-8
            parameters:
            -   name: latitude
                in: path
                description: latitude
                required: true
                type: number
                format: double
            -   name: longitude
                in: path
                description: longitude
                required: true
                type: number
                format: double
            -   name: maxdistance
                in: path
                description: maxdistance
                required: true
                type: integer
            responses:
                '200':
                    description: OK
                    schema:
                        type: object
                '204':
                    description: No coffee shop found
            deprecated: false
