@echo off

setlocal

set MICROCOFFEE_WEB_HOST=192.168.99.100

set MICROCOFFEE_WEB_PORT_LOCATION_HTTP=8081
set MICROCOFFEE_WEB_PORT_ORDER_HTTP=8082

set MICROCOFFEE_WEB_PORT_LOCATION_HTTPS=8444
set MICROCOFFEE_WEB_PORT_ORDER_HTTPS=8445

set | grep MICROCOFFEE

mvn spring-boot:run -Drun.profiles=devlocal

endlocal
