version: '3'
services:
    creditrating:
        image: dagbjorn/microcoffeeoncloud-creditrating:1.0.0-SNAPSHOT
        ports:
            - "8083:8083"
            - "8446:8446"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery

networks:
    microcoffee:
    configserver:
        external:
            name: microcoffeeoncloud-configserver_configserver
    discovery:
        external:
            name: microcoffeeoncloud-discovery_discovery
