---
apiVersion: v1
kind: Pod
metadata:
  name: microcoffee
  labels:
    app: microcoffee
spec:
  containers:
    - name: creditrating
      image: dagbjorn/microcoffeeoncloud-creditrating:1.0.0-SNAPSHOT
      ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8446
          hostPort: 8446
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "devdocker"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://192.168.99.100:8091"
          