version: '3'
services:
    discovery:
        image: dagbjorn/microcoffeeoncloud-discovery:1.0.0-SNAPSHOT
        ports:
            - "8092:8092"
            - "8455:8455"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            discovery:
                aliases:
                    - discovery.microcoffee.study
            configserver:

networks:
    discovery:
    configserver:
        external:
            name: microcoffeeoncloud-configserver_configserver
            