version: '3'
services:
    gateway:
        image: microcoffeeoncloud-gateway:1.0.0-SNAPSHOT
        ports:
            - "8080:8080"
            - "8443:8443"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery

networks:
    microcoffee:
    configserver:
        external:
            name: microcoffeeoncloudconfigserver_configserver
    discovery:
        external:
            name: microcoffeeonclouddiscovery_discovery
            