services:
    gateway:
        image: dagbjorn/microcoffeeoncloud-gateway:1.0.0-SNAPSHOT
        ports:
            # Netty (used by Spring Cloud Gateway) doesn't appear to support multiple ports.
            #- "8080:8080"
            - "8443:8443"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://configserver.microcoffee.study:8454
        domainname: microcoffee.study
        networks:
            - microcoffee
            - configserver
            - discovery

networks:
    microcoffee:
    configserver:
        name: microcoffeeoncloud-configserver_configserver
        external: true
    discovery:
        name: microcoffeeoncloud-discovery_discovery
        external: true
