---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: discovery
        image: dagbjorn/microcoffeeoncloud-gateway:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /internal/isready
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /internal/isalive
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        # Netty (used by Spring Cloud Gateway) doesn't appear to support multiple ports.
        #- containerPort: 8080
        - containerPort: 8443
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "devgke"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "https://configserver.default:8454"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
    #- port: 8080
    #  targetPort: 8080
    #  name: gateway-http
    - port: 8443
      targetPort: 8443
      name: gateway-https
  selector:
    app: gateway
    