version: '3'
services:
    keycloak:
        image: dagbjorn/microcoffeeoncloud-authserver:1.0.0-SNAPSHOT
        ports:
            - "8093:8093"
            - "8456:8456"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=/opt/microcoffee/keycloak/microcoffee-realm.json
            - MICROCOFFEE_CERT_DOMAIN=microcoffee.study
        domainname: microcoffee.study
        entrypoint: ["/opt/microcoffee/scripts/authserver-entrypoint.sh", "-b", "0.0.0.0", "-Djboss.http.port=8093", "-Djboss.https.port=8456"]
        