version: '3'
services:
    keycloak:
        image: dagbjorn/microcoffeeoncloud-authserver:1.0.0-SNAPSHOT
        ports:
          - "8093:8093"
          - "8456:8456"
        environment:
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
          - MICROCOFFEE_CERT_DOMAIN=microcoffee.study
        domainname: microcoffee.study
        entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--http-enabled=true", "--http-port=8093", "--https-port=8456", "--https-key-store-file=/opt/microcoffee/keystore/$$MICROCOFFEE_CERT_DOMAIN.p12", "--https-key-store-password=12345678"]
        networks:
            authserver:
                aliases:
                  - authserver.microcoffee.study

networks:
    authserver:
        