---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: authserver
        image: dagbjorn/microcoffeeoncloud-authserver:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        command: ["/opt/keycloak/bin/kc.sh"]
        args: ["start-dev",
               "--import-realm",
               "--http-enabled=true", "--http-port=8093",
               "--https-port=8456", "--https-key-store-file=/opt/microcoffee/keystore/wildcard.default.p12", "--https-key-store-password=12345678",
               "--http-management-port=8457",
               "--health-enabled=true", "--metrics-enabled=true"]
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8457
            scheme: HTTPS
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8457
            scheme: HTTPS
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 8093
        - containerPort: 8456
        - containerPort: 8457
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: authserver
  labels:
    app: authserver
spec:
  type: NodePort
  ports:
    - port: 8093
      targetPort: 8093
      nodePort: 30093
      name: auth-http
    - port: 8456
      targetPort: 8456
      nodePort: 30456
      name: auth-https
    - port: 8457
      targetPort: 8457
      nodePort: 30457
      name: auth-https-mgmt
  selector:
    app: authserver
