---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: dagbjorn/microcoffeeoncloud-order:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /internal/isready
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /internal/isalive
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 8082
        - containerPort: 8445
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "devgke"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "https://configserver.default:8454"
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
      name: config-http
    - port: 8445
      targetPort: 8445
      nodePort: 30445
      name: config-https
  selector:
    app: order
 