---
apiVersion: v1
kind: Pod
metadata:
  name: microcoffee
  labels:
    app: microcoffee
spec:
  containers:
    - name: order
      image: dagbjorn/microcoffeeoncloud-order:1.0.0-SNAPSHOT
      ports:
        - containerPort: 8082
          hostPort: 8082
        - containerPort: 8445
          hostPort: 8445
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "devdocker"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://192.168.99.100:8091"
    - name: creditrating
      image: dagbjorn/microcoffeeoncloud-creditrating:1.0.0-SNAPSHOT
      ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8446
          hostPort: 8446
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "devdocker"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://192.168.99.100:8091"
    - name: mongodb
      image: mongo:3.6.1
      ports:
        - containerPort: 27017
          hostPort: 27017
        - containerPort: 28017
          hostPort: 28017
      volumeMounts:
        - name: mongodbdata
          mountPath: /data/db
  volumes:
    - name: mongodbdata
      hostPath:
        path: /mnt/sda1/data/mongodbdata
