name: Create cluster on GKE
on:
  workflow_dispatch:

env:
  GKE_PROJECT: microcoffeeoncloud
  GKE_CLUSTER: microcoffeeoncloud-cluster
  GKE_ZONE: europe-west1-b

jobs:
  create-cluster:
    name: Create GKE cluster
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SRVGHA_KEY }}

      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GKE_PROJECT }}

      - name: Display current gcloud environment
        run: |-
          gcloud info

      - name: Create cluster
        run: |-
          gcloud container clusters create ${{ env.GKE_CLUSTER }} --machine-type=n1-standard-1 --num-nodes=4 --disk-size=10GB --zone=${{ env.GKE_ZONE }}
          gcloud compute instances list

      - name: Create firewall rules
        run: |-
          gcloud compute firewall-rules create microcoffee --allow tcp:30080-30099,tcp:30443-30462
          gcloud compute firewall-rules create microcoffee-database --allow tcp:30017
          gcloud compute firewall-rules list

      - name: Create MongoDB disk
        run: |-
          gcloud compute disks create mongodb-disk --size=10GB --zone=${{ env.GKE_ZONE }}
          gcloud compute disks list
