name: Create cluster on Google Kubernetes Engine
on:
  workflow_dispatch:

env:
  GKE_PROJECT: microcoffeeoncloud
  GKE_CLUSTER: microcoffeeoncloud-cluster
  GKE_ZONE: europe-west1-b

jobs:
  create-cluster:
    name: Create GKE cluster
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SRVGHA_KEY }}
          export_default_credentials: true

      # Register Docker to use the gcloud CLI as a credential helper for authentication.
      - name: Register gcloud as a Docker credential helper
        run: |-
          gcloud --quiet auth configure-docker

      - name: Create cluster
        run: |-
          gcloud info
          echo $GOOGLE_APPLICATION_CREDENTIALS
          gcloud container clusters create ${{ env.GKE_CLUSTER }} --machine-type=n1-standard-1 --num-nodes=4 --disk-size=10GB --zone=${{ env.GKE_ZONE }}
          gcloud compute instances list

      - name: Create firewall rules
        run: |-
          gcloud compute firewall-rules create microcoffee --allow tcp:30080-30099,tcp:30443-30462
          gcloud compute firewall-rules create microcoffee-database --allow tcp:30017
          gcloud compute firewall-rules listt

      - name: Create MongoDB disk
        run: |-
          gcloud compute disks create mongodb-disk --size=10GB --zone=${{ env.GKE_ZONE }}
          gcloud compute disks list
