name: Delete cluster on Google Kubernetes Engine
on:
  workflow_dispatch:

env:
  GKE_PROJECT: microcoffeeoncloud
  GKE_CLUSTER: microcoffeeoncloud-cluster
  GKE_ZONE: europe-west1-b

jobs:
  delete-cluster:
    name: Delete GKE cluster
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SRVGHA_KEY }}
          project_id: ${{ env.GKE_PROJECT }}

      - name: Display current gcloud environment
        run: |-
         gcloud info

      - name: Delete firewall rules
        run: |-
          gcloud compute firewall-rules delete microcoffee --quiet
          gcloud compute firewall-rules delete microcoffee-database --quiet
          gcloud compute firewall-rules list

      - name: Delete cluster
        run: |-
          gcloud container clusters delete ${{ env.GKE_CLUSTER }} --quiet
          gcloud compute instances list

      - name: Delete MongoDB disk
        run: |-
          gcloud compute disks delete mongodb-disk --quiet
          gcloud compute disks list
