name: Deploy Microcoffee to Google Kubernetes Engine
on:
  workflow_dispatch:

env:
  GKE_PROJECT: microcoffeoncloud
  GKE_CLUSTER: microcoffeeoncloud-cluster
  GKE_ZONE: europe-west1-b

jobs:
  deploy:
    name: Deploy to GKE cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SRVGHA_KEY }}
          project_id: ${{ env.GKE_PROJECT }}

      # Register Docker to use the gcloud CLI as a credential helper for authentication.
      - name: Register gcloud as a Docker credential helper
        run: |-
          gcloud --quiet auth configure-docker

      # https://github.com/marketplace/actions/get-gke-credentials
      - name: Get the GKE credentials so we can deploy to the cluster
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SRVGHA_KEY }}

      - name: Deploy Keycloak authorization server
        run: |-
          kubectl apply -f microcoffeeoncloud-authserver/k8s-service-gke.yml

      - name: Waiting for Keycloak authorization server to become ready
        run: |-
          kubectl wait --for=condition=Ready pod -l app=authserver --timeout=300s

      - name: Configure Keycloak authorization server
        run: |-
          export EXTERNAL_IP=$(gcloud compute instances list --project $GKE_PROJECT --format json | jq -r ".[0].networkInterfaces[0].accessConfigs[0].natIP")
          echo $EXTERNAL_IP
