name: Undeploy Microcoffee from GKE
on:
  workflow_dispatch:

env:
  GKE_PROJECT: microcoffeeoncloud
  GKE_CLUSTER: microcoffeeoncloud-cluster
  GKE_ZONE: europe-west1-b

jobs:
  undeploy:
    name: Undeploy from GKE cluster
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SRVGHA_KEY }}
          export_default_credentials: true

      - name: Display current gcloud environment
        run: |-
          gcloud info
          printenv
          cat $GOOGLE_APPLICATION_CREDENTIALS
          echo ${{ secrets.GKE_SRVGHA_KEY }} | base64 -d > $GITHUB_WORKSPACE/gke-srvgha-key.json
          cat $GITHUB_WORKSPACE/gke-srvgha-key.json

      # https://github.com/marketplace/actions/get-gke-credentials
      - name: Get GKE credentials and setup a kubeconfig file
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Undeploy all and wait for pods to terminate
        run: |-
          kubectl delete service,deployment creditrating --ignore-not-found
          kubectl delete service,deployment location --ignore-not-found
          kubectl delete service,deployment order --ignore-not-found
          kubectl delete service,deployment gateway --ignore-not-found
          kubectl delete service,deployment authserver --ignore-not-found
          kubectl delete service,deployment configserver --ignore-not-found
          kubectl delete service,deployment discovery --ignore-not-found
          kubectl delete service,deployment database --ignore-not-found
          kubectl wait --for=delete pod -l "app in (authserver,configserver,mongodb,discovery,gateway,location,order,creditrating)" --timeout=120s
